### ISSUE TITLE
Unable to open/create table

### ISSUE THREAD

**Issue by Bapf** [ludus-leonis/FreeBeeGee#1]
System: Ubuntu 18.04

When I open the site I get a "Our server is currently experiencing technical difficulties. Please try again later."
The developer console on the browser shows a 404 on the /api/ request, with the following content:

{"_error": "GENERIC_ERROR","_messages":["not found: i\/"]}

**Comment by ludus-leonis** [comment]
Can you please provide:
- the folder on the webserver the docroot is in (e.g. /var/www/myserver/docroot)
- the folder inside the docroot you installed FreeBeeGee in (e.g. /var/www/myserver/docroot/freebeegee)
- your PHP version

**Comment by Bapf** [comment]
the folder is (in both cases): /srv/www/fbg.nullniveau.org/htdocs
php version: 7.2.24-0ubuntu0.18.04.7

(EDIT: Did a short test on a ubuntu 20.04 vm (php 7.4.3-4ubuntu2.4). With this setup its working.)
(EDIT2: On a new Ubuntu 18.04 I get the "New Table" dialog, but starting a table also crashes.)

**Comment by ludus-leonis** [comment]
Thanks for the update. The folder-autodetect of the API is not working correctly for some reason in your first case and mangles the path. Tricky to reproduce, but  needs fixing for sure.

**Comment by ludus-leonis** [comment]
A few observations using a 18.04 live cd:

- default ubuntu apache2 has no mod_rewrite enabled by default (`a2enmod rewrite` + enable in serverconfig for host + restart)
- default ubuntu apache2 as no php-zip installed (probably cause of your EDIT2). needs: `apt install php-zip` (from universe repo).

Will clairfy that in the install notes and maybe introduce a "requirements checker" page/functions.

But in neither cases I could reproduce your original problem (GENERIC_ERROR on "i/"). with mod_rewrite and php-zip installed, 18.04 / php7.2 serves FreeBeeGee fine for me both in docroot and subfolder installations.

**Comment by ludus-leonis** [comment]
While updating FreeBeeGee 0.9.0 to support PHP 7.3-8.0 (7.2 is now no longer supported) I did a series of more tests, but never could reproduce this issue during any of them. Until more Information is available I'll close this ticket.

**Comment by Bapf** [comment]
Ok. Dann bin ich eh erstmal raus, weil ich hier noch Ubuntu 18.04 LTS fahre, und da ist PHP 7.2 ja noch gesetzt.
Danke trotzdem fürs nachschauen.

**Comment by ludus-leonis** [comment]
sidenote: FreeBeeGee should still contine to run on PHP 7.2 in general (and is automatically tested on that version before each release, too), as no exclusive language features from higher versions are used. It's just no longer mentioned in the README/INSTALL docs.
